menu:
  首页: /
#  文集: /collection
#  图集: /gallery
  归档: /archives
#  分类: /index.html#categories
  关于我: /resume

submenu:
 # 订阅: /atom.xml
  留言: /customization


widgets:
#- search #google search
- category
- baidu_tuijian
- archive
# - tag
- tagcloud
- weibo



sidebar:
  # Sidebar Position, available value: left | right
  #position: left
  position: right

  # Sidebar Display, available value:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  Totally remove sidebar including sidebar toggle icon.
  #display: post
  display: always
  #display: hide
  #display: remove


excerpt_link: Read More
comment_link: Comments

# header头像
avatar: https://avatars3.githubusercontent.com/u/10881023?v=3&s=460
# header右侧图片展示
# ad: https://avatars3.githubusercontent.com/u/10881023?v=3&s=460


baidu_share: true

# 请到baidu_tongji.ejs中替换代码
baidu_tongji: true

# 百度推荐小挂件，enable是否开启，id百度推荐代码id
baidu_tuijian: 
  enable: true
  id: hm_t_88638

# enable是否开启；height小挂件高度；url替换成自己的微博挂件地址，同步修改url中height的值
weibo:
  enable: true
  height: 500
  url: http://widget.weibo.com/weiboshow/index.php?language=&width=268&height=500&fansRow=1&ptype=1&speed=0&skin=1&isTitle=1&noborder=1&isWeibo=1&isFans=0&uid=1883452990&verifier=4b99344e&dpc=1

# 评论提供可以选择 duoshuo 或者 wumii，无需评论，此处不填就行。
comment_provider: duoshuo

duoshuo:
  short_name: thinerzq

wumii: 
  relateditems: false
  siteprefix: http://thinerzq.me

fancybox: true

